[package]
name = "yt-dlp"
edition = "2024"
version = "1.3.4"

authors = ["boul2gom <contact@boul2gom.fr>"]
description = "ğŸ¬ï¸ A Rust library (with auto dependencies installation) for Youtube downloading"

license = "GPL-3.0"
readme = "README.md"
documentation = "https://docs.rs/yt-dlp"
homepage = "https://github.com/boul2gom/yt-dlp"
repository = "https://github.com/boul2gom/yt-dlp"

categories = ["api-bindings", "asynchronous", "multimedia", "multimedia::audio", "multimedia::video"]
keywords = ["youtube", "downloader", "async", "yt-dlp", "youtube-dl"]

[package.metadata.docs.rs]
all-features = true

[workspace.metadata.release]
shared-version = true
tag-message = "ğŸ”– v{{version}}"
pre-release-commit-message = "ğŸš§ v{{version}}"
pre-release-replacements = [
  {file="README.md", search="yt-dlp = \".*\"", replace="yt-dlp = \"{{version}}\"", exactly=1},
  {file="README.md", search="yt-dlp = { version = \".*\", features = [\"tracing\"] }", replace="yt-dlp = { version = \"{{version}}\", features = [\"tracing\"] }", exactly=1},
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["reqwest/default", "cache"]
cache = ["dep:rusqlite"]
tracing = ["dep:tracing"]
rustls = ["reqwest/rustls-tls"]

[dependencies]
# Runtime and async dependencies
tokio = { version = "1.41.1", features = ["rt-multi-thread", "macros", "fs", "time", "process"], default-features = false }
reqwest = { version = "0.12.9", features = ["json", "stream"], default-features = false }
rusqlite = { version = "0.35.0", optional = true, features = ["bundled"] }
futures-util = "0.3.31"

# Serialization dependencies
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"

# Error handling dependencies
derive_more = { version = "1.0.0", features = ["constructor"] }
thiserror = "2.0.3"

# Audio and video dependencies
mp4ameta = "0.12.1"
id3 = "1.13.1"

# Misc and compression dependencies
ordered-float = { version = "4.5.0", features = ["serde"] }
uuid = { version = "1.16.0", features = ["v4"] }
flate2 = "1.0.34"
regex = "1.10.4"
sha2 = "0.10.8"
chrono = "0.4"
tar = "0.4.43"
zip = { version = "4.2.0", default-features = false, features = ["deflate", "time", "bzip2"] }
xz2 = "0.1.7"

# Logging dependencies
tracing = { version = "0.1.40", optional = true }
cfg-if = "1.0.0"
